import { clone } from "./clone";
import { defined } from "./defined";
import { defaultValue } from "./defaultValue";
import { DeveloperError } from './DeveloperError';
import { BaseObject } from './BaseObject';
import { CNumber } from './CNumber/CNumber';
import { CArray } from './CArray/CArray';
import { CString } from './CString/CString';
import { CFormat } from './CFormat/CFormat';
import { CStorage } from './CStorage/CStorage';
import { CCookie } from './CCookie/CCookie';
import { CRegular } from './CRegular/CRegular';
import { CUrl } from './CUrl/CUrl';
import { CDevice } from './CDevice/CDevice';
import { CBrowser } from './CBrowser/CBrowser';
import { CDataTime } from './CDataTime/CDataTime';
import { CMath3D } from './CMath3D/CMath3D';
import { CFile } from './CFile/CFile';
import { COther } from './COther/COther';
import { CNetwork } from './CNetwork/CNetwork';
import { CEvent } from './CEvent/CEvent';
declare const JSC: {
    VERSION: string;
    test: () => void;
    clone: typeof clone;
    defined: typeof defined;
    defaultValue: typeof defaultValue;
    DeveloperError: typeof DeveloperError;
    BaseObject: typeof BaseObject;
    CNumber: typeof CNumber;
    CArray: typeof CArray;
    CString: typeof CString;
    CFormat: typeof CFormat;
    CStorage: typeof CStorage;
    CCookie: typeof CCookie;
    CRegular: typeof CRegular;
    CUrl: typeof CUrl;
    CDevice: typeof CDevice;
    CBrowser: typeof CBrowser;
    CDataTime: typeof CDataTime;
    CMath3D: typeof CMath3D;
    CFile: typeof CFile;
    COther: typeof COther;
    CNetwork: typeof CNetwork;
    CEvent: typeof CEvent;
};
export default JSC;
export { clone } from "./clone";
export { defined } from "./defined";
export { defaultValue } from "./defaultValue";
export { DeveloperError } from './DeveloperError';
export { BaseObject } from './BaseObject';
export { CNumber } from './CNumber/CNumber';
export { CArray } from './CArray/CArray';
export { CString } from './CString/CString';
export { CFormat } from './CFormat/CFormat';
export { CStorage } from './CStorage/CStorage';
export { CCookie } from './CCookie/CCookie';
export { CRegular } from './CRegular/CRegular';
export { CUrl } from './CUrl/CUrl';
export { CDevice } from './CDevice/CDevice';
export { CBrowser } from './CBrowser/CBrowser';
export { CDataTime } from './CDataTime/CDataTime';
export * from './CMath3D/CMath3D';
export { CFile } from './CFile/CFile';
export { COther } from './COther/COther';
export { CNetwork } from './CNetwork/CNetwork';
export { CEvent } from './CEvent/CEvent';
//# sourceMappingURL=index.d.ts.map