import { clone } from "./clone";
import { defined } from "./defined";
import { defaultValue } from "./defaultValue";
import { DeveloperError } from './DeveloperError';
import { BaseObject } from './BaseObject';
import { CObject } from './CObject';
import { CNumber } from './CNumber';
import { CArray } from './CArray';
import { CBuffer } from './CBuffer';
import { CString } from './CString';
import { CFormat } from './CFormat';
import { CStorage } from './CStorage';
import { CCookie } from './CCookie';
import { CRegular } from './CRegular';
import { CUrl } from './CUrl';
import { CDevice } from './CDevice';
import { CBrowser } from './CBrowser';
import { CDataTime } from './CDataTime';
import { CMath3D } from './CMath3D/CMath3D';
import { CFile } from './CFile';
import { COther } from './COther';
import { CNetwork } from './CNetwork';
import { CEvent } from './CEvent';
import { CEncrypt } from './CEncrypt';
declare const JSC: {
    VERSION: string;
    test: () => void;
    clone: typeof clone;
    defined: typeof defined;
    defaultValue: typeof defaultValue;
    DeveloperError: typeof DeveloperError;
    BaseObject: typeof BaseObject;
    CObject: typeof CObject;
    CNumber: typeof CNumber;
    CArray: typeof CArray;
    CBuffer: typeof CBuffer;
    CString: typeof CString;
    CFormat: typeof CFormat;
    CStorage: typeof CStorage;
    CCookie: typeof CCookie;
    CRegular: typeof CRegular;
    CUrl: typeof CUrl;
    CDevice: typeof CDevice;
    CBrowser: typeof CBrowser;
    CDataTime: typeof CDataTime;
    CMath3D: typeof CMath3D;
    CFile: typeof CFile;
    COther: typeof COther;
    CNetwork: typeof CNetwork;
    CEvent: typeof CEvent;
    CEncrypt: typeof CEncrypt;
};
export default JSC;
export { clone } from "./clone";
export { defined } from "./defined";
export { defaultValue } from "./defaultValue";
export { DeveloperError } from './DeveloperError';
export { BaseObject } from './BaseObject';
export { CObject } from './CObject';
export { CNumber } from './CNumber';
export { CArray } from './CArray';
export { CBuffer } from './CBuffer';
export { CString } from './CString';
export { CFormat } from './CFormat';
export { CStorage } from './CStorage';
export { CCookie } from './CCookie';
export { CRegular } from './CRegular';
export { CUrl } from './CUrl';
export { CDevice } from './CDevice';
export { CBrowser } from './CBrowser';
export { CDataTime } from './CDataTime';
export * from './CMath3D/CMath3D';
export { CFile } from './CFile';
export { COther } from './COther';
export { CNetwork } from './CNetwork';
export { CEvent } from './CEvent';
export { CEncrypt } from './CEncrypt';
//# sourceMappingURL=index.d.ts.map