import { Vector4 } from "./Vector4";
export declare class Color {
    r: number;
    g: number;
    b: number;
    a: number;
    constructor(r?: number, g?: number, b?: number, a?: number);
    static NAMES: {
        aliceblue: number;
        antiquewhite: number;
        aqua: number;
        aquamarine: number;
        azure: number;
        beige: number;
        bisque: number;
        black: number;
        blanchedalmond: number;
        blue: number;
        blueviolet: number;
        brown: number;
        burlywood: number;
        cadetblue: number;
        chartreuse: number;
        chocolate: number;
        coral: number;
        cornflowerblue: number;
        cornsilk: number;
        crimson: number;
        cyan: number;
        darkblue: number;
        darkcyan: number;
        darkgoldenrod: number;
        darkgray: number;
        darkgreen: number;
        darkgrey: number;
        darkkhaki: number;
        darkmagenta: number;
        darkolivegreen: number;
        darkorange: number;
        darkorchid: number;
        darkred: number;
        darksalmon: number;
        darkseagreen: number;
        darkslateblue: number;
        darkslategray: number;
        darkslategrey: number;
        darkturquoise: number;
        darkviolet: number;
        deeppink: number;
        deepskyblue: number;
        dimgray: number;
        dimgrey: number;
        dodgerblue: number;
        firebrick: number;
        floralwhite: number;
        forestgreen: number;
        fuchsia: number;
        gainsboro: number;
        ghostwhite: number;
        gold: number;
        goldenrod: number;
        gray: number;
        green: number;
        greenyellow: number;
        grey: number;
        honeydew: number;
        hotpink: number;
        indianred: number;
        indigo: number;
        ivory: number;
        khaki: number;
        lavender: number;
        lavenderblush: number;
        lawngreen: number;
        lemonchiffon: number;
        lightblue: number;
        lightcoral: number;
        lightcyan: number;
        lightgoldenrodyellow: number;
        lightgray: number;
        lightgreen: number;
        lightgrey: number;
        lightpink: number;
        lightsalmon: number;
        lightseagreen: number;
        lightskyblue: number;
        lightslategray: number;
        lightslategrey: number;
        lightsteelblue: number;
        lightyellow: number;
        lime: number;
        limegreen: number;
        linen: number;
        magenta: number;
        maroon: number;
        mediumaquamarine: number;
        mediumblue: number;
        mediumorchid: number;
        mediumpurple: number;
        mediumseagreen: number;
        mediumslateblue: number;
        mediumspringgreen: number;
        mediumturquoise: number;
        mediumvioletred: number;
        midnightblue: number;
        mintcream: number;
        mistyrose: number;
        moccasin: number;
        navajowhite: number;
        navy: number;
        oldlace: number;
        olive: number;
        olivedrab: number;
        orange: number;
        orangered: number;
        orchid: number;
        palegoldenrod: number;
        palegreen: number;
        paleturquoise: number;
        palevioletred: number;
        papayawhip: number;
        peachpuff: number;
        peru: number;
        pink: number;
        plum: number;
        powderblue: number;
        purple: number;
        rebeccapurple: number;
        red: number;
        rosybrown: number;
        royalblue: number;
        saddlebrown: number;
        salmon: number;
        sandybrown: number;
        seagreen: number;
        seashell: number;
        sienna: number;
        silver: number;
        skyblue: number;
        slateblue: number;
        slategray: number;
        slategrey: number;
        snow: number;
        springgreen: number;
        steelblue: number;
        tan: number;
        teal: number;
        thistle: number;
        tomato: number;
        turquoise: number;
        violet: number;
        wheat: number;
        white: number;
        whitesmoke: number;
        yellow: number;
        yellowgreen: number;
    };
    isColor: boolean;
    static fromVector4: (v4: Vector4, result: Color) => Color;
    static fromBytes: (r: number, g: number, b: number, a: number, result: Color) => Color;
    static fromAlpha: (color: Color, alpha: number, result: Color) => Color;
    static fromDec: (colorDec: number, result: Color) => Color;
    getHex: () => number;
    getHexString: () => string;
    static fromHsl: (hue: number, saturation: number, lightness: number, alpha: number, result: Color) => Color;
    static fromCssColorString: (color: string, result?: Color | undefined) => Color | undefined;
    static packedLength: number;
    static byteToFloat: (number: number) => number;
    static floatToByte: (number: number) => number;
    static clone: (color: Color, result: Color) => Color | undefined;
    toString: () => string;
    toCssColorString: () => string;
    toCssHexString: () => string;
    toBytes: (result: Array<number>) => number[];
    withAlpha: (alpha: number, result: Color) => Color;
    static add: (left: Color, right: Color, result: Color) => Color;
    static subtract: (left: Color, right: Color, result: Color) => Color;
    static multiply: (left: Color, right: Color, result: Color) => Color;
    static divide: (left: Color, right: Color, result: Color) => Color;
    static mod: (left: Color, right: Color, result: Color) => Color;
    static lerp: (start: Color, end: Color, t: number, result: Color) => Color;
    static multiplyByScalar: (color: Color, scalar: number, result: Color) => Color;
    static divideByScalar: (color: Color, scalar: number, result: Color) => Color;
    equals: (c: Color) => boolean;
    static ALICEBLUE: Readonly<Color | undefined>;
    static ANTIQUEWHITE: Readonly<Color | undefined>;
    static AQUA: Readonly<Color | undefined>;
    static AQUAMARINE: Readonly<Color | undefined>;
    static AZURE: Readonly<Color | undefined>;
    static BEIGE: Readonly<Color | undefined>;
    static BISQUE: Readonly<Color | undefined>;
    static BLACK: Readonly<Color | undefined>;
    static BLANCHEDALMOND: Readonly<Color | undefined>;
    static BLUE: Readonly<Color | undefined>;
    static BLUEVIOLET: Readonly<Color | undefined>;
    static BROWN: Readonly<Color | undefined>;
    static BURLYWOOD: Readonly<Color | undefined>;
    static CADETBLUE: Readonly<Color | undefined>;
    static CHARTREUSE: Readonly<Color | undefined>;
    static CHOCOLATE: Readonly<Color | undefined>;
    static CORAL: Readonly<Color | undefined>;
    static CORNFLOWERBLUE: Readonly<Color | undefined>;
    static CORNSILK: Readonly<Color | undefined>;
    static CRIMSON: Readonly<Color | undefined>;
    static CYAN: Readonly<Color | undefined>;
    static DARKBLUE: Readonly<Color | undefined>;
    static DARKCYAN: Readonly<Color | undefined>;
    static DARKGOLDENROD: Readonly<Color | undefined>;
    static DARKGRAY: Readonly<Color | undefined>;
    static DARKGREEN: Readonly<Color | undefined>;
    static DARKGREY: Readonly<Color | undefined>;
    static DARKKHAKI: Readonly<Color | undefined>;
    static DARKMAGENTA: Readonly<Color | undefined>;
    static DARKOLIVEGREEN: Readonly<Color | undefined>;
    static DARKORANGE: Readonly<Color | undefined>;
    static DARKORCHID: Readonly<Color | undefined>;
    static DARKRED: Readonly<Color | undefined>;
    static DARKSALMON: Readonly<Color | undefined>;
    static DARKSEAGREEN: Readonly<Color | undefined>;
    static DARKSLATEBLUE: Readonly<Color | undefined>;
    static DARKSLATEGRAY: Readonly<Color | undefined>;
    static DARKSLATEGREY: Readonly<Color | undefined>;
    static DARKTURQUOISE: Readonly<Color | undefined>;
    static DARKVIOLET: Readonly<Color | undefined>;
    static DEEPPINK: Readonly<Color | undefined>;
    static DEEPSKYBLUE: Readonly<Color | undefined>;
    static DIMGRAY: Readonly<Color | undefined>;
    static DIMGREY: Readonly<Color | undefined>;
    static DODGERBLUE: Readonly<Color | undefined>;
    static FIREBRICK: Readonly<Color | undefined>;
    static FLORALWHITE: Readonly<Color | undefined>;
    static FORESTGREEN: Readonly<Color | undefined>;
    static FUCHSIA: Readonly<Color | undefined>;
    static GAINSBORO: Readonly<Color | undefined>;
    static GHOSTWHITE: Readonly<Color | undefined>;
    static GOLD: Readonly<Color | undefined>;
    static GOLDENROD: Readonly<Color | undefined>;
    static GRAY: Readonly<Color | undefined>;
    static GREEN: Readonly<Color | undefined>;
    static GREENYELLOW: Readonly<Color | undefined>;
    static GREY: Readonly<Color | undefined>;
    static HONEYDEW: Readonly<Color | undefined>;
    static HOTPINK: Readonly<Color | undefined>;
    static INDIANRED: Readonly<Color | undefined>;
    static INDIGO: Readonly<Color | undefined>;
    static IVORY: Readonly<Color | undefined>;
    static KHAKI: Readonly<Color | undefined>;
    static LAVENDER: Readonly<Color | undefined>;
    static LAVENDAR_BLUSH: Readonly<Color | undefined>;
    static LAWNGREEN: Readonly<Color | undefined>;
    static LEMONCHIFFON: Readonly<Color | undefined>;
    static LIGHTBLUE: Readonly<Color | undefined>;
    static LIGHTCORAL: Readonly<Color | undefined>;
    static LIGHTCYAN: Readonly<Color | undefined>;
    static LIGHTGOLDENRODYELLOW: Readonly<Color | undefined>;
    static LIGHTGRAY: Readonly<Color | undefined>;
    static LIGHTGREEN: Readonly<Color | undefined>;
    static LIGHTGREY: Readonly<Color | undefined>;
    static LIGHTPINK: Readonly<Color | undefined>;
    static LIGHTSEAGREEN: Readonly<Color | undefined>;
    static LIGHTSKYBLUE: Readonly<Color | undefined>;
    static LIGHTSLATEGRAY: Readonly<Color | undefined>;
    static LIGHTSLATEGREY: Readonly<Color | undefined>;
    static LIGHTSTEELBLUE: Readonly<Color | undefined>;
    static LIGHTYELLOW: Readonly<Color | undefined>;
    static LIME: Readonly<Color | undefined>;
    static LIMEGREEN: Readonly<Color | undefined>;
    static LINEN: Readonly<Color | undefined>;
    static MAGENTA: Readonly<Color | undefined>;
    static MAROON: Readonly<Color | undefined>;
    static MEDIUMAQUAMARINE: Readonly<Color | undefined>;
    static MEDIUMBLUE: Readonly<Color | undefined>;
    static MEDIUMORCHID: Readonly<Color | undefined>;
    static MEDIUMPURPLE: Readonly<Color | undefined>;
    static MEDIUMSEAGREEN: Readonly<Color | undefined>;
    static MEDIUMSLATEBLUE: Readonly<Color | undefined>;
    static MEDIUMSPRINGGREEN: Readonly<Color | undefined>;
    static MEDIUMTURQUOISE: Readonly<Color | undefined>;
    static MEDIUMVIOLETRED: Readonly<Color | undefined>;
    static MIDNIGHTBLUE: Readonly<Color | undefined>;
    static MINTCREAM: Readonly<Color | undefined>;
    static MISTYROSE: Readonly<Color | undefined>;
    static MOCCASIN: Readonly<Color | undefined>;
    static NAVAJOWHITE: Readonly<Color | undefined>;
    static NAVY: Readonly<Color | undefined>;
    static OLDLACE: Readonly<Color | undefined>;
    static OLIVE: Readonly<Color | undefined>;
    static OLIVEDRAB: Readonly<Color | undefined>;
    static ORANGE: Readonly<Color | undefined>;
    static ORANGERED: Readonly<Color | undefined>;
    static ORCHID: Readonly<Color | undefined>;
    static PALEGOLDENROD: Readonly<Color | undefined>;
    static PALEGREEN: Readonly<Color | undefined>;
    static PALETURQUOISE: Readonly<Color | undefined>;
    static PALEVIOLETRED: Readonly<Color | undefined>;
    static PAPAYAWHIP: Readonly<Color | undefined>;
    static PEACHPUFF: Readonly<Color | undefined>;
    static PERU: Readonly<Color | undefined>;
    static PINK: Readonly<Color | undefined>;
    static PLUM: Readonly<Color | undefined>;
    static POWDERBLUE: Readonly<Color | undefined>;
    static PURPLE: Readonly<Color | undefined>;
    static RED: Readonly<Color | undefined>;
    static ROSYBROWN: Readonly<Color | undefined>;
    static ROYALBLUE: Readonly<Color | undefined>;
    static SADDLEBROWN: Readonly<Color | undefined>;
    static SALMON: Readonly<Color | undefined>;
    static SANDYBROWN: Readonly<Color | undefined>;
    static SEAGREEN: Readonly<Color | undefined>;
    static SEASHELL: Readonly<Color | undefined>;
    static SIENNA: Readonly<Color | undefined>;
    static SILVER: Readonly<Color | undefined>;
    static SKYBLUE: Readonly<Color | undefined>;
    static SLATEBLUE: Readonly<Color | undefined>;
    static SLATEGRAY: Readonly<Color | undefined>;
    static SLATEGREY: Readonly<Color | undefined>;
    static SNOW: Readonly<Color | undefined>;
    static SPRINGGREEN: Readonly<Color | undefined>;
    static STEELBLUE: Readonly<Color | undefined>;
    static TAN: Readonly<Color | undefined>;
    static TEAL: Readonly<Color | undefined>;
    static THISTLE: Readonly<Color | undefined>;
    static TOMATO: Readonly<Color | undefined>;
    static TURQUOISE: Readonly<Color | undefined>;
    static VIOLET: Readonly<Color | undefined>;
    static WHEAT: Readonly<Color | undefined>;
    static WHITE: Readonly<Color | undefined>;
    static WHITESMOKE: Readonly<Color | undefined>;
    static YELLOW: Readonly<Color | undefined>;
    static YELLOWGREEN: Readonly<Color | undefined>;
    static TRANSPARENT: Readonly<Color>;
}
//# sourceMappingURL=Color.d.ts.map