import { Vector4 } from "./Vector4";
export declare class Color {
    r: number;
    g: number;
    b: number;
    a: number;
    constructor(r?: number, g?: number, b?: number, a?: number);
    static _NAMES: {
        ALICEBLUE: number;
        ANTIQUEWHITE: number;
        AQUA: number;
        AQUAMARINE: number;
        AZURE: number;
        BEIGE: number;
        BISQUE: number;
        BLACK: number;
        BLANCHEDALMOND: number;
        BLUE: number;
        BLUEVIOLET: number;
        BROWN: number;
        BURLYWOOD: number;
        CADETBLUE: number;
        CHARTREUSE: number;
        CHOCOLATE: number;
        CORAL: number;
        CORNFLOWERBLUE: number;
        CORNSILK: number;
        CRIMSON: number;
        CYAN: number;
        DARKBLUE: number;
        DARKCYAN: number;
        DARKGOLDENROD: number;
        DARKGRAY: number;
        DARKGREEN: number;
        DARKGREY: number;
        DARKKHAKI: number;
        DARKMAGENTA: number;
        DARKOLIVEGREEN: number;
        DARKORANGE: number;
        DARKORCHID: number;
        DARKRED: number;
        DARKSALMON: number;
        DARKSEAGREEN: number;
        DARKSLATEBLUE: number;
        DARKSLATEGRAY: number;
        DARKSLATEGREY: number;
        DARKTURQUOISE: number;
        DARKVIOLET: number;
        DEEPPINK: number;
        DEEPSKYBLUE: number;
        DIMGRAY: number;
        DIMGREY: number;
        DODGERBLUE: number;
        FIREBRICK: number;
        FLORALWHITE: number;
        FORESTGREEN: number;
        FUCHSIA: number;
        GAINSBORO: number;
        GHOSTWHITE: number;
        GOLD: number;
        GOLDENROD: number;
        GRAY: number;
        GREEN: number;
        GREENYELLOW: number;
        GREY: number;
        HONEYDEW: number;
        HOTPINK: number;
        INDIANRED: number;
        INDIGO: number;
        IVORY: number;
        KHAKI: number;
        LAVENDER: number;
        LAVENDERBLUSH: number;
        LAWNGREEN: number;
        LEMONCHIFFON: number;
        LIGHTBLUE: number;
        LIGHTCORAL: number;
        LIGHTCYAN: number;
        LIGHTGOLDENRODYELLOW: number;
        LIGHTGRAY: number;
        LIGHTGREEN: number;
        LIGHTGREY: number;
        LIGHTPINK: number;
        LIGHTSALMON: number;
        LIGHTSEAGREEN: number;
        LIGHTSKYBLUE: number;
        LIGHTSLATEGRAY: number;
        LIGHTSLATEGREY: number;
        LIGHTSTEELBLUE: number;
        LIGHTYELLOW: number;
        LIME: number;
        LIMEGREEN: number;
        LINEN: number;
        MAGENTA: number;
        MAROON: number;
        MEDIUMAQUAMARINE: number;
        MEDIUMBLUE: number;
        MEDIUMORCHID: number;
        MEDIUMPURPLE: number;
        MEDIUMSEAGREEN: number;
        MEDIUMSLATEBLUE: number;
        MEDIUMSPRINGGREEN: number;
        MEDIUMTURQUOISE: number;
        MEDIUMVIOLETRED: number;
        MIDNIGHTBLUE: number;
        MINTCREAM: number;
        MISTYROSE: number;
        MOCCASIN: number;
        NAVAJOWHITE: number;
        NAVY: number;
        OLDLACE: number;
        OLIVE: number;
        OLIVEDRAB: number;
        ORANGE: number;
        ORANGERED: number;
        ORCHID: number;
        PALEGOLDENROD: number;
        PALEGREEN: number;
        PALETURQUOISE: number;
        PALEVIOLETRED: number;
        PAPAYAWHIP: number;
        PEACHPUFF: number;
        PERU: number;
        PINK: number;
        PLUM: number;
        POWDERBLUE: number;
        PURPLE: number;
        REBECCAPURPLE: number;
        RED: number;
        ROSYBROWN: number;
        ROYALBLUE: number;
        SADDLEBROWN: number;
        SALMON: number;
        SANDYBROWN: number;
        SEAGREEN: number;
        SEASHELL: number;
        SIENNA: number;
        SILVER: number;
        SKYBLUE: number;
        SLATEBLUE: number;
        SLATEGRAY: number;
        SLATEGREY: number;
        SNOW: number;
        SPRINGGREEN: number;
        STEELBLUE: number;
        TAN: number;
        TEAL: number;
        THISTLE: number;
        TOMATO: number;
        TURQUOISE: number;
        VIOLET: number;
        WHEAT: number;
        WHITE: number;
        WHITESMOKE: number;
        YELLOW: number;
        YELLOWGREEN: number;
    };
    isColor: boolean;
    static fromVector4: (v4: Vector4, result: Color) => Color;
    static fromBytes: (r: number, g: number, b: number, a: number, result: Color) => Color;
    static fromAlpha: (color: Color, alpha: number, result: Color) => Color;
    static fromDec: (colorDec: number, result: Color) => Color;
    static fromHex: (colorDec: number, result: Color) => Color;
    getHex: () => number;
    getHexString: () => string;
    static fromHsl: (hue: number, saturation: number, lightness: number, alpha: number, result: Color) => Color;
    static fromCssColorString: (color: string, result?: Color | undefined) => Color | undefined;
    static packedLength: number;
    static byteToFloat: (number: number) => number;
    static floatToByte: (number: number) => number;
    static clone: (color: Color, result: Color) => Color | undefined;
    toString: () => string;
    toCssColorString: () => string;
    toCssHexString: () => string;
    toBytes: (result: Array<number>) => number[];
    withAlpha: (alpha: number, result: Color) => Color;
    static add: (left: Color, right: Color, result: Color) => Color;
    static subtract: (left: Color, right: Color, result: Color) => Color;
    static multiply: (left: Color, right: Color, result: Color) => Color;
    static divide: (left: Color, right: Color, result: Color) => Color;
    static mod: (left: Color, right: Color, result: Color) => Color;
    static lerp: (start: Color, end: Color, t: number, result: Color) => Color;
    static multiplyByScalar: (color: Color, scalar: number, result: Color) => Color;
    static divideByScalar: (color: Color, scalar: number, result: Color) => Color;
    equals: (c: Color) => boolean;
    static ALICEBLUE: Readonly<Color | undefined>;
    static ANTIQUEWHITE: Readonly<Color | undefined>;
    static AQUA: Readonly<Color | undefined>;
    static AQUAMARINE: Readonly<Color | undefined>;
    static AZURE: Readonly<Color | undefined>;
    static BEIGE: Readonly<Color | undefined>;
    static BISQUE: Readonly<Color | undefined>;
    static BLACK: Readonly<Color | undefined>;
    static BLANCHEDALMOND: Readonly<Color | undefined>;
    static BLUE: Readonly<Color | undefined>;
    static BLUEVIOLET: Readonly<Color | undefined>;
    static BROWN: Readonly<Color | undefined>;
    static BURLYWOOD: Readonly<Color | undefined>;
    static CADETBLUE: Readonly<Color | undefined>;
    static CHARTREUSE: Readonly<Color | undefined>;
    static CHOCOLATE: Readonly<Color | undefined>;
    static CORAL: Readonly<Color | undefined>;
    static CORNFLOWERBLUE: Readonly<Color | undefined>;
    static CORNSILK: Readonly<Color | undefined>;
    static CRIMSON: Readonly<Color | undefined>;
    static CYAN: Readonly<Color | undefined>;
    static DARKBLUE: Readonly<Color | undefined>;
    static DARKCYAN: Readonly<Color | undefined>;
    static DARKGOLDENROD: Readonly<Color | undefined>;
    static DARKGRAY: Readonly<Color | undefined>;
    static DARKGREEN: Readonly<Color | undefined>;
    static DARKGREY: Readonly<Color | undefined>;
    static DARKKHAKI: Readonly<Color | undefined>;
    static DARKMAGENTA: Readonly<Color | undefined>;
    static DARKOLIVEGREEN: Readonly<Color | undefined>;
    static DARKORANGE: Readonly<Color | undefined>;
    static DARKORCHID: Readonly<Color | undefined>;
    static DARKRED: Readonly<Color | undefined>;
    static DARKSALMON: Readonly<Color | undefined>;
    static DARKSEAGREEN: Readonly<Color | undefined>;
    static DARKSLATEBLUE: Readonly<Color | undefined>;
    static DARKSLATEGRAY: Readonly<Color | undefined>;
    static DARKSLATEGREY: Readonly<Color | undefined>;
    static DARKTURQUOISE: Readonly<Color | undefined>;
    static DARKVIOLET: Readonly<Color | undefined>;
    static DEEPPINK: Readonly<Color | undefined>;
    static DEEPSKYBLUE: Readonly<Color | undefined>;
    static DIMGRAY: Readonly<Color | undefined>;
    static DIMGREY: Readonly<Color | undefined>;
    static DODGERBLUE: Readonly<Color | undefined>;
    static FIREBRICK: Readonly<Color | undefined>;
    static FLORALWHITE: Readonly<Color | undefined>;
    static FORESTGREEN: Readonly<Color | undefined>;
    static FUCHSIA: Readonly<Color | undefined>;
    static GAINSBORO: Readonly<Color | undefined>;
    static GHOSTWHITE: Readonly<Color | undefined>;
    static GOLD: Readonly<Color | undefined>;
    static GOLDENROD: Readonly<Color | undefined>;
    static GRAY: Readonly<Color | undefined>;
    static GREEN: Readonly<Color | undefined>;
    static GREENYELLOW: Readonly<Color | undefined>;
    static GREY: Readonly<Color | undefined>;
    static HONEYDEW: Readonly<Color | undefined>;
    static HOTPINK: Readonly<Color | undefined>;
    static INDIANRED: Readonly<Color | undefined>;
    static INDIGO: Readonly<Color | undefined>;
    static IVORY: Readonly<Color | undefined>;
    static KHAKI: Readonly<Color | undefined>;
    static LAVENDER: Readonly<Color | undefined>;
    static LAVENDAR_BLUSH: Readonly<Color | undefined>;
    static LAWNGREEN: Readonly<Color | undefined>;
    static LEMONCHIFFON: Readonly<Color | undefined>;
    static LIGHTBLUE: Readonly<Color | undefined>;
    static LIGHTCORAL: Readonly<Color | undefined>;
    static LIGHTCYAN: Readonly<Color | undefined>;
    static LIGHTGOLDENRODYELLOW: Readonly<Color | undefined>;
    static LIGHTGRAY: Readonly<Color | undefined>;
    static LIGHTGREEN: Readonly<Color | undefined>;
    static LIGHTGREY: Readonly<Color | undefined>;
    static LIGHTPINK: Readonly<Color | undefined>;
    static LIGHTSEAGREEN: Readonly<Color | undefined>;
    static LIGHTSKYBLUE: Readonly<Color | undefined>;
    static LIGHTSLATEGRAY: Readonly<Color | undefined>;
    static LIGHTSLATEGREY: Readonly<Color | undefined>;
    static LIGHTSTEELBLUE: Readonly<Color | undefined>;
    static LIGHTYELLOW: Readonly<Color | undefined>;
    static LIME: Readonly<Color | undefined>;
    static LIMEGREEN: Readonly<Color | undefined>;
    static LINEN: Readonly<Color | undefined>;
    static MAGENTA: Readonly<Color | undefined>;
    static MAROON: Readonly<Color | undefined>;
    static MEDIUMAQUAMARINE: Readonly<Color | undefined>;
    static MEDIUMBLUE: Readonly<Color | undefined>;
    static MEDIUMORCHID: Readonly<Color | undefined>;
    static MEDIUMPURPLE: Readonly<Color | undefined>;
    static MEDIUMSEAGREEN: Readonly<Color | undefined>;
    static MEDIUMSLATEBLUE: Readonly<Color | undefined>;
    static MEDIUMSPRINGGREEN: Readonly<Color | undefined>;
    static MEDIUMTURQUOISE: Readonly<Color | undefined>;
    static MEDIUMVIOLETRED: Readonly<Color | undefined>;
    static MIDNIGHTBLUE: Readonly<Color | undefined>;
    static MINTCREAM: Readonly<Color | undefined>;
    static MISTYROSE: Readonly<Color | undefined>;
    static MOCCASIN: Readonly<Color | undefined>;
    static NAVAJOWHITE: Readonly<Color | undefined>;
    static NAVY: Readonly<Color | undefined>;
    static OLDLACE: Readonly<Color | undefined>;
    static OLIVE: Readonly<Color | undefined>;
    static OLIVEDRAB: Readonly<Color | undefined>;
    static ORANGE: Readonly<Color | undefined>;
    static ORANGERED: Readonly<Color | undefined>;
    static ORCHID: Readonly<Color | undefined>;
    static PALEGOLDENROD: Readonly<Color | undefined>;
    static PALEGREEN: Readonly<Color | undefined>;
    static PALETURQUOISE: Readonly<Color | undefined>;
    static PALEVIOLETRED: Readonly<Color | undefined>;
    static PAPAYAWHIP: Readonly<Color | undefined>;
    static PEACHPUFF: Readonly<Color | undefined>;
    static PERU: Readonly<Color | undefined>;
    static PINK: Readonly<Color | undefined>;
    static PLUM: Readonly<Color | undefined>;
    static POWDERBLUE: Readonly<Color | undefined>;
    static PURPLE: Readonly<Color | undefined>;
    static RED: Readonly<Color | undefined>;
    static ROSYBROWN: Readonly<Color | undefined>;
    static ROYALBLUE: Readonly<Color | undefined>;
    static SADDLEBROWN: Readonly<Color | undefined>;
    static SALMON: Readonly<Color | undefined>;
    static SANDYBROWN: Readonly<Color | undefined>;
    static SEAGREEN: Readonly<Color | undefined>;
    static SEASHELL: Readonly<Color | undefined>;
    static SIENNA: Readonly<Color | undefined>;
    static SILVER: Readonly<Color | undefined>;
    static SKYBLUE: Readonly<Color | undefined>;
    static SLATEBLUE: Readonly<Color | undefined>;
    static SLATEGRAY: Readonly<Color | undefined>;
    static SLATEGREY: Readonly<Color | undefined>;
    static SNOW: Readonly<Color | undefined>;
    static SPRINGGREEN: Readonly<Color | undefined>;
    static STEELBLUE: Readonly<Color | undefined>;
    static TAN: Readonly<Color | undefined>;
    static TEAL: Readonly<Color | undefined>;
    static THISTLE: Readonly<Color | undefined>;
    static TOMATO: Readonly<Color | undefined>;
    static TURQUOISE: Readonly<Color | undefined>;
    static VIOLET: Readonly<Color | undefined>;
    static WHEAT: Readonly<Color | undefined>;
    static WHITE: Readonly<Color | undefined>;
    static WHITESMOKE: Readonly<Color | undefined>;
    static YELLOW: Readonly<Color | undefined>;
    static YELLOWGREEN: Readonly<Color | undefined>;
    static TRANSPARENT: Readonly<Color>;
}
//# sourceMappingURL=Color.d.ts.map